apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-app-deployment
  labels:
    app: msa-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-app
  template:
    metadata:
      labels:
        app: msa-app
    spec:
      containers:
        - name: msa-app
          image: msa-app:latest            # local image loaded into kind in CI
          imagePullPolicy: Never           # important for kind (use local image)
          ports:
            - containerPort: 80

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
